# -*- coding: utf-8 -*-
"""redes Clase C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ost3arBcVYy9ObKoiTvS4UHCgM8qkNSp
"""

host = int(input(" ingrece la cantidad de host : "))
ip = str(input(" ingrece la direccion ip : "))
red=0
a = 0
mask=0
contador = 0

# MASCARA 30
if host == 4:
    mask = (2 ** 7) + (2 ** 6) + (2 ** 5) + (2 ** 4) + (2 ** 3) + (2 ** 2)
    print(f"255.255.255.{mask} /30")
    print(f"1.1.1.1.1.1.0.0")
    red = 2**6
    print("Cantidad de redes = ",red)
    print(f"cantidad de host {4}")
    while contador <= mask:
        print(f"{ip}.{a}     {ip}.{a + 1}      {ip}.{a + 2}    {ip}.{a + 3}")
        a = a + host
        contador = contador+4

# MASCARA 29
if host >= 5 and host <= 8:
    mask = (2 ** 7) + (2 ** 6) + (2 ** 5) + (2 ** 4) + (2 ** 3)
    host = 8
    print(f"255.255.255.{mask} /29")
    print(f"1.1.1.1.1.0.0.0")
    red = 2 ** 5
    print("Cantidad de redes = ", red)
    print(f"cantidad de host {8}")
    while contador <= mask:
        print(f"{ip}.{a}     {ip}.{a + 1}      {ip}.{a + 6}    {ip}.{a + 7}")
        a = a + host
        contador = contador+8


# MASCARA 28
if host >= 9 and host <= 16:
    mask = (2 ** 7) + (2 ** 6) + (2 ** 5) + (2 ** 4)
    host = 16
    print(f"255.255.255.{mask} /28")
    print(f"1.1.1.1.0.0.0.0")
    red = 2 ** 4
    print("Cantidad de redes = ", red)
    print(f"cantidad de host {16}")
    while contador <= mask:
        print(f"{ip}.{a}     {ip}.{a + 1}      {ip}.{a + 14}    {ip}.{a + 15}")
        a = a + host
        contador = contador+16


# MASCARA 27
if host >= 17 and host <= 32:
    mask = (2 ** 7) + (2 ** 6) + (2 ** 5)
    host = 32
    print(f"255.255.255.{mask} /27")
    print(f"1.1.1.0.0.0.0.0")
    red = 2 ** 3
    print("Cantidad de redes = ", red)
    print(f"cantidad de host {32}")
    while contador <= mask:
        print(f"{ip}.{a}     {ip}.{a + 1}     {ip}.{a + 30}    {ip}.{a + 31}")
        a = a + host
        contador = contador+32


# MASCARA 26
if host >= 33 and host <= 64:
    mask = (2 ** 7) + (2 ** 6)
    host = 64
    print(f"255.255.255.{mask} /26")
    print(f"1.1.0.0.0.0.0.0")
    red = 2 ** 2
    print("Cantidad de redes = ", red)
    print(f"cantidad de host {64}")
    while contador <= mask:
        print(f"{ip}.{a}     {ip}.{a + 1}      {ip}.{a + 62}    {ip}.{a + 63}")
        a = a + host
        contador = contador+64



# MASCARA 25
if host >= 65 and host <= 128:
    mask = (2 ** 7)
    host = 128
    print(f"255.255.255.{mask} /25")
    print(f"1.0.0.0.0.0.0.0")
    red = 2 ** 1
    print("Cantidad de redes = ", red)
    print(f"cantidad de host {128}")
    while contador <= mask:
        print(f"{ip}.{a}     {ip}.{a + 1}      {ip}.{a + 126}    {ip}.{a + 127}")
        a = a + host
        contador = contador+128


# MASCARA 24
if host >= 129 and host <= 256:
    mask = 0
    host = 256
    print(f"255.255.255.{mask} /24")
    print(f"0.0.0.0.0.0.0.0")
    red = 2 ** 0
    print("Cantidad de redes = ", red)
    print(f"cantidad de host {256}")
    while contador <= mask:
        print(f"{ip}.{a}     {ip}.{a + 1}      {ip}.{a + 254}    {ip}.{a + 255}")
        a = a + host
        contador = contador+256